filter:
    excluded_paths: [vendor/*]
checks:
    php:
      avoid_usage_of_logical_operators: false
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                concatenation: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 1
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, Tests/]
    php_cpd:
        enabled: true