filter:
    excluded_paths: [vendor/*]
checks:
    php:
      avoid_usage_of_logical_operators: false
      encourage_single_quotes: true
      return_doc_comments: true
      simplify_boolean_return: true
      return_doc_comment_if_not_inferrable: true
      check_method_contracts:
          verify_documented_constraints: true
          verify_parent_constraints: true
      uppercase_constants: true
      remove_extra_empty_lines: true
      properties_in_camelcaps: true
      prefer_while_loop_over_for_loop: true
      parameter_doc_comments: true
      no_new_line_at_end_of_file: true
      no_goto: true
      align_assignments: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            around_operators:
                concatenation: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 1
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, Tests/]
    php_cpd:
        enabled: true